### ISSUE TITLE
take out .pov file to put it in init folder and enable changes

### ISSUE THREAD

**Issue by Cnstant** [Cnstant/simulateur_ironcar#8]

**Comment by FabienArcellier** [comment]
En tant que coureur Ironcar, je veux pouvoir configurer le simulateur pour reproduire le comportement de
la caméra de la voiture.

## Implémentation

* la commande ``simulateur_ironcar init`` initialise un fichier ``camera.pov`` au format povray.

```
.
├── configuration.json
├── camera.pov
├── ground
│   └── default.jpg
├── photos
```

Le fichier ``camera.pov`` par défaut sera celui de l'octonomous. Il sera amené à évoluer.

```
#version 3.7;
#include "colors.inc"

global_settings { assumed_gamma 1.0 }

camera {
  ultra_wide_angle
  location <500, 60, 0>
  look_at  <500, 50, 100>
}
box {
  <0, 0, 0>,
  < 1000, 1000, 1000>
  // http://www.f-lohmueller.de/pov_tut/backgrnd/p_sky9.htm
  texture {
    uv_mapping
    pigment {
      image_map {
        jpeg "{{ simulateur_ironcar_placeholder }}" once map_type 0
      }
    }
  }
}
light_source { <500, 500, 500> color White}
```
* changement de version du fichier configuration.json. Le simulateur prendra la version 1.1 et il ne sera plus rétrocompatible avec les anciennes versions.

* une commande ``simulateur_ironcar validate`` vérifie que le dossier de travail est valide pour procéder à la génération :

  * le fichier configuration.json est valide pour la version du programme
  * le fichier camera.pov existe
  * le fichier camera.pov contient la variable {{ simulateur_ironcar_placeholder }}
  * le fichier camera.pov peut etre processé par povray

## outputs de ``simulateur_ironcar validate``

Si la commande ``simulateur_ironcar validate`` valide le contenu du dossier de travail, elle se termine avec le code 0, sinon 1.

```
- V1: configuration.json is present [OK]
- V2 : configuration.json is parsed [OK]
- V3 : configuration.json contains ``version`` attribute [OK]
- V4: camera.pov is present [OK]
- V5: camera.pov contains the placeholder variable {{ simulateur_ironcar_placeholder }} [OK]
- V6: camera.pov is parsed properly with povray [OK]
```
En cas de défaillance d'une des règles de validation, plus d'information sont affichés pour aider au diagnostique.

## validation du template ``camera.pov`` sur l'intégration continue

les règles de validation (V4 - V6) sont exécuté lors du packaging de simulateur_ironcar dans ``travis.ci`` dans la suite de test ``tests/acceptances/test_profil_generation_template.py``.
