### ISSUE TITLE
Parallelize image generation 

### ISSUE THREAD

**Issue by Cnstant** [Cnstant/simulateur_ironcar#9]

**Comment by FabienArcellier** [comment]
Je recommande de développer cette parallélisation à partir d'un pattern de producer/consumer en utilisant une queue simple comme redis.

* [Producer/consumer pattern](https://dzone.com/articles/producer-consumer-pattern)

Ce snippet décrit parfaitement le pattern : https://gist.github.com/igniteflow/1870027

# Implémentation

* ajoutez 2 commandes dans simulateur_ironcar
* refactorer pictures_generation pour supporter le pattern producer / consumer

``simulateur_ironcar producer --queue localhost:6379`` alimente une queue à partir des jobs qui sont construits dans le module ``simulator/pictures_generation.py``. La configuration povray devra être envoyé par redis dans le message. Une fois la liste des jobs envoyés, ajouter un marqueur de fin de traitement dans redis.

Dans le job, envoyez :

* les paramètres (voir pictures_generation.py)
* le fichier povray
* l'espace d'écriture (s3 ou filesystem) - utiliser une uri et la parser avec ``urllib.parse``

``simulateur_ironcar worker --queue localhost:6379`` dépile les jobs présents dans la queue et invoque povray pour générer les images. Si la liste des jobs est vide et que le marqueur de fin de traitement est présent, arrêtez les workers.

# Testabilité

* Tests d'acceptance : Tu peux utiliser une interface Queue et avoir 2 implémentations (code d'infrastructure) : un avec Redis, un en InMemory.

* Tests d'intégration : monter une instance de Redis avec docker et valider les opérations de lecture / ecriture
